# Generated by Django 4.1.7 on 2023-04-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(max_length=64, verbose_name="Модель телефона"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Цена"
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="Изображение")),
                ("release_date", models.DateField()),
                ("lte_exists", models.BooleanField()),
                ("slug", models.SlugField(max_length=255, verbose_name="URL")),
            ],
        ),
    ]
